version: '3'
services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - HTTP_PORT='80'
      - HTTP_HOST='localhost'
      - HTTP_SCHEMA='http'
      - POSTGRES_DSN='postgres://postgres:qwerty@localhost:5432/postgres?sslmode=disable'

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password